name: Report a bug
description: Create a bug report to help us improve [REPO_NAME]
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the outcome
      description: |
        Describe the problem in as much detail as possible.
        Tip: You can attach images or log files by clicking on this area to highlight it and then dragging files into it.
      placeholder: |
        Step to reproduce the bug :
          1. do the thing
          2. do the thing
          3. do the thing
          4. Here is the bug
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Bug priority
      description: Please be realistic. If you need to expand on your reasoning, please use the Problem Description field above.
      options:
        - Low (slightly annoying)
        - Medium (annoying)
        - High (annoying for all users)
    validations:
      required: true
